# Generated by Django 3.0.8 on 2020-07-24 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20200724_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='is_an_artist',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
