# Generated by Django 3.0.8 on 2020-07-24 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_customuser_is_an_artist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='is_an_artist',
            field=models.BooleanField(default=False),
        ),
    ]
