# Generated by Django 3.0.8 on 2020-07-28 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('newsletter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettermembers',
            name='receive_email',
            field=models.BooleanField(blank=True, default=True),
        ),
    ]
